###
POST http://localhost:8080/process_json
Content-Type: application/json

{
  "message": "CREATE"
}

###
POST http://localhost:8080/process_json
Content-Type: application/json

{
  "message": "CREATE DATABASE"
}

###
POST http://localhost:8080/process_json
Content-Type: application/json

{
  "message": "CREATE DATABASE;"
}

###
POST http://localhost:8080/process_json
Content-Type: application/json

{
  "message": "CREATE DATABASE ali"
}

###
POST http://localhost:8080/process_json
Content-Type: application/json

{
  "message": "CREATE DATABASE ali;"
}

###
POST http://localhost:8080/process_json
Content-Type: application/json

{
  "message": "CREATE DATABASE ali;"
}
