###
POST http://localhost:8080/process_json
Content-Type: application/json

{
  "message": "RENAME"
}

###
POST http://localhost:8080/process_json
Content-Type: application/json

{
  "message": "RENAME DATABASE"
}

###
POST http://localhost:8080/process_json
Content-Type: application/json

{
  "message": "RENAME DATABASE ;"
}

###
POST http://localhost:8080/process_json
Content-Type: application/json

{
  "message": "RENAME DATABASE ali,ali2"
}

###
POST http://localhost:8080/process_json
Content-Type: application/json

{
  "message": "RENAME DATABASE ali,ali2;"
}

