POST http://localhost:8080/checkt
Content-Type: application/json

{
  "token": "59947dd8bacc1ae545dd89a506ca64860d053bfd41d02d91a37babb77a4ed767"
}

###
###
POST http://localhost:8080/ca
Content-Type: application/json

{
  "username": "subhankhaild",
  "password": "W1231243@"
}

###
POST http://localhost:8080/ln
Content-Type: application/json

{
  "username": "subhankhaild",
  "password": "W1231243@"
}

###

# curl -X POST "http://127.0.0.1:8000/ca" -H "Content-Type: application/json" -d '{"username": "waleedzafar", "password": "W12345678@"}'
POST http://localhost:8080/ca
Content-Type: application/json

{
  "username": "waleedzafar",
  "password": "W12345678@"
}



###

POST http://localhost:8080/ln
Content-Type: application/json

{
  "username": "waleedzafar",
  "password": "W12345678@"
}

###
POST http://localhost:8080/pq
Content-Type: application/json

{
  "token": "b3455d2ad296811e7f7f12af846d72df24cdc34b6de38f08282d52414a994a83",
  "query": "CREATE DATABASE third;"
}

###
POST http://localhost:8080/pq
Content-Type: application/json

{
  "token": "",
  "query": "SHOW DATABASE;"
}

