POST http://localhost:8080/checkt
Content-Type: application/json

{
  "token": "cc00e837af5798b50bb800a15ea3f83cdd01bb71e443e17d362a5df43d8fcffe"
}

###
POST http://localhost:4000/ln
Content-Type: application/json

{
  "username": "jawadali",
  "password": "W12345678@"
}


###

POST http://localhost:8080/ln
Content-Type: application/json

{
  "username": "waleedzafar",
  "password": "W12345678@"
}


###

POST http://localhost:8080/ln
Content-Type: application/json

{
  "username": "jawadali",
  "password": "W12345678@"
}