[package]
name = "compiler"
version = "0.1.0"
edition = "2021"


[dependencies]
storagecontroller = { version = "0.1.0", path = "../storagecontroller" }
triadic_error = { version = "0.1.0", path = "../triadic_error" }
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
