
###
POST http://localhost:8080/pq
Content-Type: application/json

{
  "token": "0beca3154a253cca46d7cf3336061fc36391c41432ccd8aa3726bc8cdfb68420",
  "query": "CREATE DATABASE no;"
}

###
POST http://localhost:8080/pq
Content-Type: application/json

{
  "token": "d64032f755b734bb4688e89926eb78c765b45b7abc2d8cd9becbc4564a011c7f",
  "query": "SHOW DATABASE;"
}

###
POST http://localhost:8080/sdb
Content-Type: application/json

{
  "token": "d64032f755b734bb4688e89926eb78c765b45b7abc2d8cd9becbc4564a011c7f",
  "database_name": "third4"
}

