###
POST http://localhost:8080/pq
Content-Type: application/json

{
  "token": "0beca3154a253cca46d7cf3336061fc36391c41432ccd8aa3726bc8cdfb68420",
  "query": "CREATE TABLE Persons (PersonID INT,LastName STRING,FirstName STRING,Address STRING);"
}


###
POST http://localhost:8080/pq
Content-Type: application/json

{
  "token": "0beca3154a253cca46d7cf3336061fc36391c41432ccd8aa3726bc8cdfb68420",
  "query": "CREATE TABLE Persons (PersonID INT,LastName STRING UNIQUE,FirstName STRING );"
}


###