###
POST http://localhost:8080/pq
Content-Type: application/json

{
  "token": "0beca3154a253cca46d7cf3336061fc36391c41432ccd8aa3726bc8cdfb68420",
  "query": "CREATE TABLE Persons (PersonID INT,LastName STRING,FirstName STRING,Address STRING);"
}


###
POST http://localhost:8080/pq
Content-Type: application/json

{
  "token": "deb0651ae98ae6765fd1ec13f3d988104285ceb130a96b995d1daf1826d86cc2",
  "query": "CREATE TABLE STUDENT(ID INT PRIMARY KEY,NAME STRING,Gender CHAR,Background TEXT,Fee FLOAT,Allowed BOOLEAN);"
}



###


###
POST http://localhost:8080/pq
Content-Type: application/json

{
  "token": "deb0651ae98ae6765fd1ec13f3d988104285ceb130a96b995d1daf1826d86cc2",
  "query": "INSERT INTO STUDENT(ID,NAME,Gender,Background,Fee,Allowed) VALUES(1:L,'ALI':T,'M':T ,'Vip person':L ,200.1 :T,true:T),(2:F,'Nomi':T,'M':T,'Vip person1':L,200.1:T,true:T),(3:T,'Mahnoor':F,'F':L,'Nothing person':L,100.0:L,false:L);"

}

###
POST http://localhost:8080/pq
Content-Type: application/json

{
  "token": "55c79456e7cfdd1427a2c33bcef270c4617cfa803a32532284f6a05ce21bd2eb",
  "query": "SELECT * FROM STUDENT;"

}


###